import { Header } from "@/components/Header"

export default function home() {
  return (
    <div className="grid grid-rows-[auto_1fr_auto] h-full w-full">
      <Header />
      <main>
        <article className="columns-2">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Posuere lorem ipsum dolor sit amet consectetur. Et ultrices neque ornare aenean euismod elementum. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Netus et malesuada fames ac turpis egestas integer eget aliquet. Non diam phasellus vestibulum lorem sed risus ultricies. Tellus mauris a diam maecenas sed enim ut. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Euismod quis viverra nibh cras pulvinar mattis.

          Magna eget est lorem ipsum. At volutpat diam ut venenatis tellus in metus. Nulla porttitor massa id neque. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Turpis massa tincidunt dui ut ornare lectus sit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Non curabitur gravida arcu ac tortor. Pharetra pharetra massa massa ultricies mi quis. Nunc pulvinar sapien et ligula ullamcorper. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Consectetur adipiscing elit ut aliquam. Nulla pharetra diam sit amet nisl. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Nulla pharetra diam sit amet nisl suscipit adipiscing. Eget aliquet nibh praesent tristique magna sit amet. Id cursus metus aliquam eleifend mi in nulla. Ac placerat vestibulum lectus mauris.

          Donec enim diam vulputate ut pharetra sit amet aliquam id. Cursus turpis massa tincidunt dui ut ornare lectus. Dui sapien eget mi proin sed libero. Ac placerat vestibulum lectus mauris ultrices eros in. Vestibulum sed arcu non odio euismod lacinia at quis risus. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Aliquam sem et tortor consequat id. Convallis posuere morbi leo urna molestie at elementum eu. Lorem sed risus ultricies tristique nulla aliquet. Mattis molestie a iaculis at erat. Blandit turpis cursus in hac habitasse platea dictumst quisque. Sit amet facilisis magna etiam tempor. Ut consequat semper viverra nam libero justo laoreet sit. Amet porttitor eget dolor morbi non arcu risus quis. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Id porta nibh venenatis cras. Ultrices tincidunt arcu non sodales. Sit amet commodo nulla facilisi nullam.
          o

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Posuere lorem ipsum dolor sit amet consectetur. Et ultrices neque ornare aenean euismod elementum. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Netus et malesuada fames ac turpis egestas integer eget aliquet. Non diam phasellus vestibulum lorem sed risus ultricies. Tellus mauris a diam maecenas sed enim ut. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Euismod quis viverra nibh cras pulvinar mattis.

          Magna eget est lorem ipsum. At volutpat diam ut venenatis tellus in metus. Nulla porttitor massa id neque. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Turpis massa tincidunt dui ut ornare lectus sit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Non curabitur gravida arcu ac tortor. Pharetra pharetra massa massa ultricies mi quis. Nunc pulvinar sapien et ligula ullamcorper. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Consectetur adipiscing elit ut aliquam. Nulla pharetra diam sit amet nisl. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Nulla pharetra diam sit amet nisl suscipit adipiscing. Eget aliquet nibh praesent tristique magna sit amet. Id cursus metus aliquam eleifend mi in nulla. Ac placerat vestibulum lectus mauris.

          Donec enim diam vulputate ut pharetra sit amet aliquam id. Cursus turpis massa tincidunt dui ut ornare lectus. Dui sapien eget mi proin sed libero. Ac placerat vestibulum lectus mauris ultrices eros in. Vestibulum sed arcu non odio euismod lacinia at quis risus. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Aliquam sem et tortor consequat id. Convallis posuere morbi leo urna molestie at elementum eu. Lorem sed risus ultricies tristique nulla aliquet. Mattis molestie a iaculis at erat. Blandit turpis cursus in hac habitasse platea dictumst quisque. Sit amet facilisis magna etiam tempor. Ut consequat semper viverra nam libero justo laoreet sit. Amet porttitor eget dolor morbi non arcu risus quis. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Id porta nibh venenatis cras. Ultrices tincidunt arcu non sodales. Sit amet commodo nulla facilisi nullam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Posuere lorem ipsum dolor sit amet consectetur. Et ultrices neque ornare aenean euismod elementum. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Netus et malesuada fames ac turpis egestas integer eget aliquet. Non diam phasellus vestibulum lorem sed risus ultricies. Tellus mauris a diam maecenas sed enim ut. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Euismod quis viverra nibh cras pulvinar mattis.

          Magna eget est lorem ipsum. At volutpat diam ut venenatis tellus in metus. Nulla porttitor massa id neque. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Turpis massa tincidunt dui ut ornare lectus sit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Non curabitur gravida arcu ac tortor. Pharetra pharetra massa massa ultricies mi quis. Nunc pulvinar sapien et ligula ullamcorper. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Consectetur adipiscing elit ut aliquam. Nulla pharetra diam sit amet nisl. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Nulla pharetra diam sit amet nisl suscipit adipiscing. Eget aliquet nibh praesent tristique magna sit amet. Id cursus metus aliquam eleifend mi in nulla. Ac placerat vestibulum lectus mauris.

          Donec enim diam vulputate ut pharetra sit amet aliquam id. Cursus turpis massa tincidunt dui ut ornare lectus. Dui sapien eget mi proin sed libero. Ac placerat vestibulum lectus mauris ultrices eros in. Vestibulum sed arcu non odio euismod lacinia at quis risus. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Aliquam sem et tortor consequat id. Convallis posuere morbi leo urna molestie at elementum eu. Lorem sed risus ultricies tristique nulla aliquet. Mattis molestie a iaculis at erat. Blandit turpis cursus in hac habitasse platea dictumst quisque. Sit amet facilisis magna etiam tempor. Ut consequat semper viverra nam libero justo laoreet sit. Amet porttitor eget dolor morbi non arcu risus quis. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Id porta nibh venenatis cras. Ultrices tincidunt arcu non sodales. Sit amet commodo nulla facilisi nullam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Posuere lorem ipsum dolor sit amet consectetur. Et ultrices neque ornare aenean euismod elementum. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Netus et malesuada fames ac turpis egestas integer eget aliquet. Non diam phasellus vestibulum lorem sed risus ultricies. Tellus mauris a diam maecenas sed enim ut. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Euismod quis viverra nibh cras pulvinar mattis.

          Magna eget est lorem ipsum. At volutpat diam ut venenatis tellus in metus. Nulla porttitor massa id neque. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Turpis massa tincidunt dui ut ornare lectus sit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Non curabitur gravida arcu ac tortor. Pharetra pharetra massa massa ultricies mi quis. Nunc pulvinar sapien et ligula ullamcorper. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Consectetur adipiscing elit ut aliquam. Nulla pharetra diam sit amet nisl. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Nulla pharetra diam sit amet nisl suscipit adipiscing. Eget aliquet nibh praesent tristique magna sit amet. Id cursus metus aliquam eleifend mi in nulla. Ac placerat vestibulum lectus mauris.

          Donec enim diam vulputate ut pharetra sit amet aliquam id. Cursus turpis massa tincidunt dui ut ornare lectus. Dui sapien eget mi proin sed libero. Ac placerat vestibulum lectus mauris ultrices eros in. Vestibulum sed arcu non odio euismod lacinia at quis risus. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Aliquam sem et tortor consequat id. Convallis posuere morbi leo urna molestie at elementum eu. Lorem sed risus ultricies tristique nulla aliquet. Mattis molestie a iaculis at erat. Blandit turpis cursus in hac habitasse platea dictumst quisque. Sit amet facilisis magna etiam tempor. Ut consequat semper viverra nam libero justo laoreet sit. Amet porttitor eget dolor morbi non arcu risus quis. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Id porta nibh venenatis cras. Ultrices tincidunt arcu non sodales. Sit amet commodo nulla facilisi nullam.
        </article>
      </main>
      <footer className="border border-t-black text-center">
        Made with love by Aaryan.
      </footer>
    </div>
  )
}
